const en = {
  language: { label: "Language", english: "English", hindi: "हिंदी" },
  nav: { services: "Services", howItWorks: "How It Works", forWorkers: "For Workers", about: "About Us", login: "Login", home: "Home", myBookings: "My Bookings", myProfile: "My Profile", newRequest: "New Request" },
  common: { back: "Back", dashboard: "Dashboard", view: "View", saveProfile: "Save Profile", bookWorker: "Book Worker", confirmed: "Confirmed", pending: "Pending", service: "Service", worker: "Worker", date: "Date", time: "Time", location: "Location", price: "Price", estimatedPrice: "Estimated Price", yourLocation: "Your Location" },
  services: { plumbing: "Plumbing", electrical: "Electrical", cleaning: "Cleaning", carpentry: "Carpentry", gardening: "Gardening", care: "Care Services", plumbingDescription: "Repairs, installation & maintenance", electricalDescription: "Safe electrical repair & installation", cleaningDescription: "Professional home cleaning services", carpentryDescription: "Furniture repair & woodwork", gardeningDescription: "Garden care & maintenance", careDescription: "Trusted assistance for families" },
  home: {
    badge: "🤝 Cooperative Powered Services", title: "Trusted Services.", titleAccent: "Fair Wages.", description: "Connect with verified local service professionals through a cooperative-powered platform built for communities.", yourLocation: "Your location", whatNeed: "What do you need?", searchServices: "Search services", findService: "Find a Service", verifiedWorkers: "✓ Verified Workers", transparentPricing: "✓ Transparent Pricing", communityFirst: "✓ Community First", imageAlt: "Sahāyu service professional", trustedProfessionals: "Trusted Professionals", readyToHelp: "Ready to help your community", servicesLabel: "OUR SERVICES", servicesTitle: "Everything you need,", servicesAccent: "near you.", servicesDescription: "Find skilled and verified cooperative workers for everyday household needs.", whyLabel: "WHY SAHĀYU?", whyTitle: "A better way to work", whyAccent: "together.", whyDescription: "Sahāyu connects households with cooperative workers, creating a transparent ecosystem where workers, customers and communities grow together.", explore: "Explore Sahāyu", verifiedBenefitTitle: "Verified Workers", verifiedBenefitDescription: "Connect with skilled and cooperative-verified professionals.", fairTitle: "Fair & Transparent", fairDescription: "Clear pricing and transparent worker earnings.", cooperativeTitle: "Cooperative First", cooperativeDescription: "Workers are part of the community they serve.", howLabel: "HOW IT WORKS", howTitle: "Get help in", howAccent: "three simple steps.", stepOneTitle: "Choose a Service", stepOneDescription: "Tell us what service you need.", stepTwoTitle: "Find a Worker", stepTwoDescription: "Choose from verified nearby professionals.", stepThreeTitle: "Book & Relax", stepThreeDescription: "Book your service and track the request.", workerLabel: "FOR WORKERS", workerTitle: "Your skills.", workerMiddle: "Your community.", workerAccent: "Your opportunity.", workerDescription: "Join your local cooperative network and connect with households looking for your skills.", joinWorker: "Join as a Worker", footer: "Cooperative-powered services for stronger communities.", copyright: "© 2026 Sahāyu · Built for SIH 2026"
  },
  login: { title: "Welcome to", description: "Choose how you want to use Sahāyu.", customerTitle: "I'm a Customer", customerDescription: "Find trusted workers for your household needs.", workerTitle: "I'm a Worker", workerDescription: "Find local opportunities and grow your work.", backHome: "← Back to Home" },
  customer: { label: "CUSTOMER", title: "Find the right", titleAccent: "worker.", description: "Tell us what you need and we'll help you find verified local professionals.", requestTitle: "Request a Service", selectService: "Select a service", enterLocation: "Enter your location", preferredDate: "Preferred Date", preferredTime: "Preferred Time", selectTime: "Select time", morning: "Morning", afternoon: "Afternoon", evening: "Evening", describeRequirement: "Describe your requirement", requirementPlaceholder: "Tell the worker what you need...", findWorkers: "Find Workers", whyTitle: "Why choose Sahāyu?", verifiedLocal: "Verified local workers", transparentPricing: "Transparent pricing", communityTrusted: "Community trusted professionals", safeBookings: "Safe and reliable bookings" },
  workers: { label: "VERIFIED WORKERS", backRequest: "← Back to Request", title: "Choose your", titleAccent: "worker.", description: "Skilled professionals from your local cooperative community.", verified: "✓ VERIFIED", nearby: "📍 Nearby", startingFrom: "Starting from", trustTitle: "Community-powered trust", trustDescription: "Every worker on Sahāyu is part of our cooperative network.", jobs: "{count} jobs", plumbingSpecialist: "Plumbing Specialist", electricalTechnician: "Electrical Technician", cleaningExpert: "Home Cleaning Expert", carpentrySpecialist: "Carpentry Specialist" },
  worker: { label: "WORKER DASHBOARD", welcome: "Welcome back,", welcomeAccent: "Worker.", description: "Manage your services, requests and earnings from one place.", activeJobs: "Active Jobs", thisMonth: "This Month", yourRating: "Your Rating", recentRequests: "Recent Requests", editProfile: "Edit Profile", kitchenRepair: "Kitchen Pipe Repair", fanInstallation: "Fan Installation", nearbyToday: "📍 Nearby · Today", tomorrow: "📍 2.4 km · Tomorrow", estimated: "₹{amount} estimated", growTitle: "Grow with Sahāyu", growDescription: "Build your reputation and connect with more customers in your community.", manageProfile: "Manage Profile" },
  profile: { label: "WORKER PROFILE", title: "Your professional", titleAccent: "profile.", fullName: "Full Name", phone: "Phone", primarySkill: "Primary Skill", experience: "Experience", about: "About You", available: "Available for work", availableDescription: "Customers can see you when you're available.", buildTrust: "Build trust", buildTrustDescription: "A complete profile helps customers understand your experience and choose you with confidence.", verifiedTip: "✓ Verified workers get more visibility" },
  booking: { label: "BOOKING", title: "Confirm your", titleAccent: "booking.", requestTitle: "Service Request", review: "Review the details before confirming.", finalPricing: "💡 Final pricing will be confirmed with the worker before the service begins.", confirm: "Confirm Booking", plumbingService: "Plumbing Service", bookingPlaced: "✓ Your booking has been successfully placed.", bookAnother: "Book Another Service", myLabel: "MY BOOKINGS", myTitle: "Your", myTitleAccent: "bookings.", myDescription: "Track your service requests and bookings.", dateValue: "28 August 2026" }
};

export default en;
