const hi = {
  language: { label: "भाषा", english: "English", hindi: "हिंदी" },
  nav: { services: "सेवाएँ", howItWorks: "यह कैसे काम करता है", forWorkers: "कामगारों के लिए", about: "हमारे बारे में", login: "लॉग इन", home: "होम", myBookings: "मेरी बुकिंग", myProfile: "मेरी प्रोफ़ाइल", newRequest: "नई रिक्वेस्ट" },
  common: { back: "वापस", dashboard: "डैशबोर्ड", view: "देखें", saveProfile: "प्रोफ़ाइल सेव करें", bookWorker: "कामगार बुक करें", confirmed: "पुष्ट", pending: "लंबित", service: "सेवा", worker: "कामगार", date: "तारीख", time: "समय", location: "स्थान", price: "कीमत", estimatedPrice: "अनुमानित कीमत", yourLocation: "आपका स्थान" },
  services: { plumbing: "प्लंबिंग", electrical: "इलेक्ट्रिकल", cleaning: "सफाई", carpentry: "बढ़ईगिरी", gardening: "बागवानी", care: "देखभाल सेवाएँ", plumbingDescription: "मरम्मत, इंस्टॉलेशन और रखरखाव", electricalDescription: "सुरक्षित इलेक्ट्रिकल मरम्मत और इंस्टॉलेशन", cleaningDescription: "पेशेवर घरेलू सफाई सेवाएँ", carpentryDescription: "फर्नीचर मरम्मत और लकड़ी का काम", gardeningDescription: "बगीचे की देखभाल और रखरखाव", careDescription: "परिवारों के लिए भरोसेमंद सहायता" },
  home: { badge: "🤝 सहकारी सेवाओं से सशक्त", title: "भरोसेमंद सेवाएँ।", titleAccent: "उचित मेहनताना।", description: "समुदायों के लिए बने सहकारी मंच के ज़रिए सत्यापित स्थानीय सेवा पेशेवरों से जुड़ें।", yourLocation: "आपका स्थान", whatNeed: "आपको क्या चाहिए?", searchServices: "सेवाएँ खोजें", findService: "सेवा खोजें", verifiedWorkers: "✓ सत्यापित कामगार", transparentPricing: "✓ पारदर्शी कीमतें", communityFirst: "✓ समुदाय सबसे पहले", imageAlt: "Sahāyu सेवा पेशेवर", trustedProfessionals: "भरोसेमंद पेशेवर", readyToHelp: "आपके समुदाय की मदद के लिए तैयार", servicesLabel: "हमारी सेवाएँ", servicesTitle: "जो भी चाहिए,", servicesAccent: "आपके पास।", servicesDescription: "रोज़मर्रा की घरेलू ज़रूरतों के लिए कुशल और सत्यापित सहकारी कामगार खोजें।", whyLabel: "सहायु क्यों?", whyTitle: "मिलकर काम करने का", whyAccent: "बेहतर तरीका।", whyDescription: "Sahāyu घरों को सहकारी कामगारों से जोड़ता है और ऐसा पारदर्शी तंत्र बनाता है जिसमें कामगार, ग्राहक और समुदाय साथ बढ़ते हैं।", explore: "Sahāyu देखें", verifiedBenefitTitle: "सत्यापित कामगार", verifiedBenefitDescription: "कुशल और सहकारी संस्था से सत्यापित पेशेवरों से जुड़ें।", fairTitle: "उचित और पारदर्शी", fairDescription: "स्पष्ट कीमतें और कामगारों की पारदर्शी कमाई।", cooperativeTitle: "सहकारिता पहले", cooperativeDescription: "कामगार उसी समुदाय का हिस्सा हैं जिसकी वे सेवा करते हैं।", howLabel: "यह कैसे काम करता है", howTitle: "मदद पाएँ", howAccent: "तीन आसान चरणों में।", stepOneTitle: "सेवा चुनें", stepOneDescription: "हमें बताएं कि आपको कौन-सी सेवा चाहिए।", stepTwoTitle: "कामगार खोजें", stepTwoDescription: "पास के सत्यापित पेशेवरों में से चुनें।", stepThreeTitle: "बुक करें और निश्चिंत रहें", stepThreeDescription: "अपनी सेवा बुक करें और रिक्वेस्ट की स्थिति देखें।", workerLabel: "कामगारों के लिए", workerTitle: "आपके कौशल।", workerMiddle: "आपका समुदाय।", workerAccent: "आपका अवसर।", workerDescription: "अपने स्थानीय सहकारी नेटवर्क से जुड़ें और आपके कौशल ढूंढ रहे घरों से मिलें।", joinWorker: "कामगार के रूप में जुड़ें", footer: "मज़बूत समुदायों के लिए सहकारी सेवाएँ।", copyright: "© 2026 Sahāyu · SIH 2026 के लिए बनाया गया" },
  login: { title: "Sahāyu में आपका स्वागत है", description: "चुनें कि आप Sahāyu का उपयोग कैसे करना चाहते हैं।", customerTitle: "मैं ग्राहक हूँ", customerDescription: "अपने घर की ज़रूरतों के लिए भरोसेमंद कामगार खोजें।", workerTitle: "मैं कामगार हूँ", workerDescription: "स्थानीय अवसर खोजें और अपना काम बढ़ाएँ।", backHome: "← होम पर वापस जाएँ" },
  customer: { label: "ग्राहक", title: "सही", titleAccent: "कामगार खोजें।", description: "हमें अपनी ज़रूरत बताएं और हम आपको सत्यापित स्थानीय पेशेवर खोजने में मदद करेंगे।", requestTitle: "सेवा के लिए रिक्वेस्ट करें", selectService: "सेवा चुनें", enterLocation: "अपना स्थान दर्ज करें", preferredDate: "पसंदीदा तारीख", preferredTime: "पसंदीदा समय", selectTime: "समय चुनें", morning: "सुबह", afternoon: "दोपहर", evening: "शाम", describeRequirement: "अपनी ज़रूरत बताएं", requirementPlaceholder: "कामगार को बताएं कि आपको क्या चाहिए...", findWorkers: "कामगार खोजें", whyTitle: "Sahāyu क्यों चुनें?", verifiedLocal: "सत्यापित स्थानीय कामगार", transparentPricing: "पारदर्शी कीमतें", communityTrusted: "समुदाय के भरोसेमंद पेशेवर", safeBookings: "सुरक्षित और भरोसेमंद बुकिंग" },
  workers: { label: "सत्यापित कामगार", backRequest: "← रिक्वेस्ट पर वापस जाएँ", title: "अपना", titleAccent: "कामगार चुनें।", description: "अपने स्थानीय सहकारी समुदाय के कुशल पेशेवर।", verified: "✓ सत्यापित", nearby: "📍 पास में", startingFrom: "शुरुआती कीमत", trustTitle: "समुदाय की ताकत से भरोसा", trustDescription: "Sahāyu का हर कामगार हमारे सहकारी नेटवर्क का हिस्सा है।", jobs: "{count} काम", plumbingSpecialist: "प्लंबिंग विशेषज्ञ", electricalTechnician: "इलेक्ट्रिकल टेक्नीशियन", cleaningExpert: "घरेलू सफाई विशेषज्ञ", carpentrySpecialist: "बढ़ईगिरी विशेषज्ञ" },
  worker: { label: "कामगार डैशबोर्ड", welcome: "वापसी पर स्वागत है,", welcomeAccent: "कामगार।", description: "अपनी सेवाएँ, रिक्वेस्ट और कमाई एक ही जगह से संभालें।", activeJobs: "चालू काम", thisMonth: "इस महीने", yourRating: "आपकी रेटिंग", recentRequests: "हाल की रिक्वेस्ट", editProfile: "प्रोफ़ाइल बदलें", kitchenRepair: "किचन पाइप मरम्मत", fanInstallation: "पंखा इंस्टॉलेशन", nearbyToday: "📍 पास में · आज", tomorrow: "📍 2.4 किमी · कल", estimated: "₹{amount} अनुमानित", growTitle: "Sahāyu के साथ आगे बढ़ें", growDescription: "अपनी पहचान बनाएं और समुदाय में ज़्यादा ग्राहकों से जुड़ें।", manageProfile: "प्रोफ़ाइल संभालें" },
  profile: { label: "कामगार प्रोफ़ाइल", title: "आपकी पेशेवर", titleAccent: "प्रोफ़ाइल।", fullName: "पूरा नाम", phone: "फ़ोन", primarySkill: "मुख्य कौशल", experience: "अनुभव", about: "अपने बारे में", available: "काम के लिए उपलब्ध", availableDescription: "जब आप उपलब्ध होंगे, ग्राहक आपको देख सकेंगे।", buildTrust: "भरोसा बनाएं", buildTrustDescription: "एक पूरी प्रोफ़ाइल ग्राहकों को आपका अनुभव समझने और भरोसे से चुनने में मदद करती है।", verifiedTip: "✓ सत्यापित कामगारों को ज़्यादा दिखने का मौका मिलता है" },
  booking: { label: "बुकिंग", title: "अपनी बुकिंग", titleAccent: "पुष्ट करें।", requestTitle: "सेवा रिक्वेस्ट", review: "पुष्टि करने से पहले विवरण देखें।", finalPricing: "💡 सेवा शुरू होने से पहले कामगार के साथ अंतिम कीमत तय होगी।", confirm: "बुकिंग पुष्ट करें", plumbingService: "प्लंबिंग सेवा", bookingPlaced: "✓ आपकी बुकिंग सफलतापूर्वक हो गई है।", bookAnother: "एक और सेवा बुक करें", myLabel: "मेरी बुकिंग", myTitle: "आपकी", myTitleAccent: "बुकिंग।", myDescription: "अपनी सेवा रिक्वेस्ट और बुकिंग की स्थिति देखें।", dateValue: "28 अगस्त 2026" }
};

export default hi;
